version: '3.8'

services:
  grassland_inference:
    build:
      context: .
      dockerfile: Dockerfile-cpu
    image: grasslandnetwork/inference_container-cpu:latest
    environment:
      - PIPELESS_USER_PYTHON_PACKAGES=opencv-python,numpy
    command: start --stages-dir .
    ports:
      - "3030:3030"
    
  mediamtx:
    image: bluenviron/mediamtx:latest
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=localhost
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    stdin_open: true # Imitates '-it', allows keeping the stdin open
    tty: true # Allocates a pseudo-TTY, imitating '-it'
    depends_on:
      - grassland_inference

