version: '3.8'

services:
  grassland_inference:
    build:
      context: .
      dockerfile: Dockerfile-cpu
    image: grasslandnetwork/inference_container-cpu:latest
    environment:
      - PIPELESS_USER_PYTHON_PACKAGES=opencv-python,numpy
    command: start --stages-dir .
    network_mode: host
    
  mediamtx:
    image: bluenviron/mediamtx:latest
    network_mode: host
    stdin_open: true # Imitates '-it', allows keeping the stdin open
    tty: true # Allocates a pseudo-TTY, imitating '-it'
    depends_on:
      - grassland_inference

