# Stage 1: Build environment
FROM miguelaeh/pipeless:latest

# Ensure user is set to Pipeless' default user
USER 1001

WORKDIR /

# Temporarily switch to root for elevated permissions
USER root
RUN python3 -m venv /.venv

# Activate the virtual environment and install packages
RUN . /.venv/bin/activate && pip install --no-cache-dir opencv-python numpy

RUN chown -R 1001:1001 /.venv

# set the user back to Pipeless' default user
USER 1001

COPY my_project /app

# Reset to the Pipeless' default working directory
WORKDIR /app
